# Generated by Django 3.1.2 on 2021-07-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_client_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
