# Generated by Django 3.1.2 on 2021-09-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
